# Generated by Django 3.1.4 on 2021-01-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
